"""
Problem 2
"""


jumlah_produk = int(input("Banyaknya produkyang akan di proses: "))
mesin_1_per_detik = int(input("Kemampuan kerja mesin pertama: "))
mesin_2_per_detik = int(input("Kemampuan kerja mesin kedua: "))
mesin_3_per_detik = int(input("Kemampuan kerja mesin ketiga: "))


"""
100

100 / 15 

3000 / 10 = 300 

jumlah  | 70 | 40 | 10 | 10
detik   |  1 |  2 |  3 | 4  | 5  | 6  |  7 |  8 |  9 | 10  |  
mesin 1 | 10 | 10 | 10 | 5  |
mesin 2 | 20 | 20 | 20 | 5  |
hasil   | 30 | 50 | 80 | 80 | 70 | 60 | 50 | 40 | 30 | 20  |
mesin 3 |    | 10 | 20 | 30 | 40 | 50 | 60 | 70 | 80 | 90 | 100 | 
"""
